/**
 * The "Air pump & cylinder" sample: a hand pump, a valve and a 2 × 11
 * cylinder from the reviewed 2015 Arocs (42043) definitions on an original
 * stand, with a loose crate to push. Its LDraw text (with the embedded CCAL
 * definitions) is generated by scripts/pneumatic-sample-node.ts into
 * fixtures/ldraw/templates/air-pump.mpd and loads on demand, like the
 * build-script samples. Play admits the air circuit by itself (see
 * src/play/pneumatic-play-source.ts); only the crate is an authored rig.
 */
import { occurrences } from "../core/document";
import { AppError, type Project, type Vec3 } from "../core/types";
import { importLDraw } from "../ldraw/io";
import type { MotionRig } from "../mechanisms/types";

export const AIR_PUMP_SAMPLE = {
  name: "air-pump",
  file: "air-pump.mpd",
  title: "Air pump & cylinder",
  hint: "Open Controls. Hold Pump, then set the valve to Push out to shove the crate.",
} as const;
const CRATE_MODEL = "air-pump - crate.ldr";

let source: string | undefined;
export function registerAirPumpSource(text: string) {
  source = text;
}
export const airPumpSourceLoaded = () => source !== undefined;

export function airPumpProject(): Project {
  if (source === undefined)
    throw new AppError(
      "INVALID_INPUT",
      `The ${AIR_PUMP_SAMPLE.title} sample loads on demand: open it with loadTemplate()`,
    );
  const project = importLDraw(source, AIR_PUMP_SAMPLE.file);
  project.title = AIR_PUMP_SAMPLE.title;
  project.scene = { backdrop: "studio", playHint: AIR_PUMP_SAMPLE.hint };
  const crate = occurrences(project).filter((o) => o.modelId === CRATE_MODEL);
  if (crate.length !== 3) throw new Error("Air pump crate not found");
  const xs = crate.map((o) => o.transform.position[0]),
    zs = crate.map((o) => o.transform.position[2]);
  const frame: Vec3 = [
    (Math.min(...xs) + Math.max(...xs)) / 2,
    -4,
    (Math.min(...zs) + Math.max(...zs)) / 2,
  ];
  // Three stud-joined parts: a loose gravity object, like the playground's
  // crates. Mass is a declared simulation setting.
  const rig: MotionRig = {
    schemaVersion: 1,
    id: "crate",
    name: "Crate",
    mode: "kinematic",
    groups: [
      {
        id: "body",
        occurrenceIds: crate.map((o) => o.id),
        frame: { position: frame, basis: [1, 0, 0, 0, 1, 0, 0, 0, 1] },
        restTransforms: Object.fromEntries(
          crate.map((o) => [o.id, structuredClone(o.transform)]),
        ),
      },
    ],
    joints: [],
    dynamics: {
      groups: { body: { anchored: false, massKg: 5 } },
      startDynamic: true,
    },
  };
  project.motionRigs = { crate: rig };
  return project;
}
